import Link from 'next/link';
import {PRICES,BRAND_NAME,formatPrice} from '@/data/config';
import {categories} from '@/data/categories';
import {ContactLinks} from './ContactLinks';
export function HowItWorks(){return <section className="section how"><div className="section-heading"><div><p className="eyebrow">03 / КАК ЭТО РАБОТАЕТ</p><h2>От вашей идеи<br/><em>до одной красивой ссылки.</em></h2></div><p>Три простых шага.<br/>Всё остальное мы берём на себя.</p></div><div className="steps">{[['Выберите дизайн','Найдите вариант, который подходит именно вам.'],['Отправьте данные','Имена, дату, фотографии, текст и место проведения.'],['Получите готовый сайт','Мы всё настроим и отправим вашу персональную ссылку.']].map(([t,d],i)=><div key={t}><span>0{i+1}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section>}
export function Features(){return <section className="features section"><div><p className="eyebrow">ПРОДУМАНО ДО МЕЛОЧЕЙ</p><h2>Всё, что нужно —<br/><em>в одном приглашении.</em></h2><p>Красота, которая умеет быть полезной.<br/>Ваши гости найдут всю информацию по одной ссылке.</p></div><div className="feature-list">{['Фотографии','Музыка','Дата и время','Таймер до события','Адрес и 2ГИС','RSVP','Dress Code','Программа вечера','История пары','Пожелания','Анимации','Ваши тексты'].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span>{x}</div>)}</div></section>}
export function Pricing(){return <section className="section" id="pricing"><div className="section-heading"><div><p className="eyebrow">04 / СТОИМОСТЬ</p><h2>Особенное —<br/><em>не значит сложное.</em></h2></div><p>Выберите готовую композицию<br/>или создайте свою с чистого листа.</p></div><div className="pricing-grid">{[{name:'Готовый дизайн',price:PRICES.ready,items:['Выбранный дизайн','Ваши имена и дата','Фотографии и текст','Адрес мероприятия','Адаптация под телефон']},{name:'Индивидуальный',price:PRICES.custom,items:['Уникальный дизайн','Индивидуальные анимации','Дополнительные блоки','Нестандартный функционал','Дизайн под вашу идею']}].map((p,i)=><article className={`pricing-card ${i?'dark':''}`} key={p.name}><p className="eyebrow">{i?'СОЗДАНО ТОЛЬКО ДЛЯ ВАС':'ВАША ИСТОРИЯ, НАША КОЛЛЕКЦИЯ'}</p><h3>{p.name}</h3><p className="pricing-value"><small>от</small> {formatPrice(p.price)}</p><ul>{p.items.map(x=><li key={x}>✓ <span>{x}</span></li>)}</ul>{i?<Link className="button" href="/custom">Обсудить идею ↗</Link>:<Link className="button" href="#collections">Выбрать дизайн ↗</Link>}</article>)}</div></section>}
export function Benefits(){return <section className="benefits section"><p className="eyebrow">МЕНЬШЕ БУМАГИ. БОЛЬШЕ ВОЗМОЖНОСТЕЙ.</p><h2>Почему цифровое приглашение?</h2><div>{['Не нужно печатать','Легко отправить в WhatsApp и Instagram','Всегда под рукой','Карта и музыка внутри','Информацию можно изменить'].map(x=><p key={x}><span>✧</span>{x}</p>)}</div></section>}
const faqs=[['Можно ли изменить дизайн?','Да. В готовом дизайне мы заменим тексты и фотографии. Изменения композиции обсудим отдельно.'],['Можно ли добавить свои фотографии?','Конечно. Вы отправляете фотографии, а мы подбираем для них гармоничное расположение.'],['Можно ли добавить музыку?','Да. Музыка включается по нажатию гостя, с учётом ограничений браузера.'],['Можно ли добавить адрес 2ГИС?','Да. Добавим адрес и ссылку, которая открывает место проведения в 2ГИС.'],['Как гости получают приглашение?','Вы отправляете персональную ссылку через WhatsApp, Instagram или любой удобный мессенджер.'],['Сколько времени занимает создание?','Срок согласуем до начала работы. Он зависит от выбранного дизайна и готовности материалов.'],['Можно ли сделать полностью индивидуальный сайт?','Да. Расскажите о вашей идее — обсудим оформление, функционал, сроки и стоимость.']];
export function FAQ(){return <section className="section faq"><div><p className="eyebrow">05 / ЧАСТЫЕ ВОПРОСЫ</p><h2>Немного деталей<br/><em>перед началом.</em></h2></div><div>{faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>}
export function CTA(){return <section className="cta"><p className="eyebrow">ВАША ИСТОРИЯ МОЖЕТ БЫТЬ ДРУГОЙ</p><h2>Не нашли <em>тот самый</em> дизайн?</h2><p>Создадим приглашение специально для вас.</p><div><Link href="/custom" className="button">Индивидуальный дизайн ↗</Link><div className="cta-contacts"><p>Связаться с нами</p><ContactLinks/></div></div></section>}
export function Footer(){return <footer className="footer"><div><Link className="brand" href="/">{BRAND_NAME}<span>digital atelier</span></Link><p>Цифровые приглашения<br/>для особенных моментов.</p></div><nav>{categories.map(c=><Link key={c.slug} href={`/${c.slug}`}>{c.label}</Link>)}</nav><div className="footer-contact"><ContactLinks/></div><div className="footer-bottom"><span>© 2026 {BRAND_NAME}</span><span>С вниманием к каждой истории.</span></div></footer>}
